<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle("Главная");
?><?$APPLICATION->IncludeComponent(
	"bitrix:main.auth.form",
	"",
Array()
);?><?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');
?>